### ISSUE TITLE
发现个坑

### ISSUE THREAD

**Issue by Elip-kio** [OCNYang/PageTransformerHelp#11]
大家用了这个库以后不要使用R.id.viewPager，会和这个库冲突。感觉作者也可以考虑下这个问题

**Comment by OCNYang** [comment]
在Android中不同页面使用相同的id是允许的，只要不是在同一个页面，应该不存在ID冲突的情况，  
你遇到的问题是怎样的？确认一下你通过id获取控件时引用的布局是否正确（Kotlin 有可能引用错误）。

**Comment by Elip-kio** [comment]
我的app有四个tab，第四个使用了PageTransformerHelp，第二个里面有个viewPager给的id是R.id.viewPager。然后出现的问题是如果先打开第四个tab，再打开第二个tab，第二个Tab里的viewPager就失效了。把R.id.viewPager改成其他的则一切正常
